import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  { href: '/', label: 'Home' },
  { href: 'docs', label: 'Docs' },
  { href: '/todos', label: 'Todos' },
]

// RootLayout name can be anything you want
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* any page[s].tsx inside app */}
      {/* LAYOUT never rerendered even the route change, it is cached */}
      {/*
      //! Can't parse data down from layout to children through props
      */}
      <body className={inter.className}>
        <header>
          <nav>
            <ul className="flex items-center gap-4">
              {links.map((link) => (
                // take use of nextjs navigation feature with smart router (pre-fetching, clientside routeing ....)
                <li key={link.href}>
                  <Link href={link.href}>{link.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
